[general]
provider = "wikimedia" # bing, unsplash, wikimedia
location = "downloads"
daemon = false

# Documentation from third party tools
# https://github.com/genzj/pybingwallpaper
# https://github.com/goodtrailer/daily-desktop/blob/main/DailyDesktop.Providers.Bing/BingProvider.cs
[bing]
size = "UHD" # UHD, 1920x1080, 1280x720, 640x480
country = "us"
market = "en-US"

# https://unsplash.com/oauth/applications
[unsplash] # If unset, will scrape
application_id = ""
access_key = ""
secret_key = ""

# https://api.wikimedia.org/wiki/Getting_featured_content_from_Wikipedia_with_Python#Today's_featured_article
[wikimedia]
authorization = "" # Not required, but recommended
user_agent = "" # Not required, but recommended